services:
  - type: web
    name: nutrition-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        value: "362423055"
      - key: PORT
        value: "10000"
      - key: YANDEX_FOLDER_ID
        sync: false
      - key: YANDEX_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: nutrition-bot
          property: url
